export enum TemplateType {
  Bloc = 'bloc.tmpl',
  Event = 'event.tmpl',
  Model = 'model.tmpl',
  Page = 'page.tmpl',
  Provider = 'provider.tmpl',
  Repository = 'repository.tmpl',
  Screen = 'screen.tmpl',
  State = 'state.tmpl',
  Index = 'index.tmpl',
  LcfarmContract = 'lcfarm_contract.tmpl',
  LcfarmPresenter = 'lcfarm_presenter.tmpl',
  LcfarmModel = 'lcfarm_model.tmpl',
  LcfarmPage = 'lcfarm_page.tmpl',
}
